- name: AsaCoco Insurance
  type: Entry-type AsaCoco
  image: insurance.png
  price: 1000
  cm:
    id: OCGCgUmpd8k
    start_time: 957
    end_time: 1109
- name: AsaCoco Antenna
  type: Transmission-type AsaCoco
  image: antenna.jpeg
  srp: 2000
  price: 1000
  cm:
    id: RPEntBOmgi4
    start_time: 685
    end_time: 861
- name: AsaCoco Mist
  type: Air Filling Type AsaCoco
  image: mist.png
  price: 1000
  cm:
    id: kHsCSYBBSFc
    start_time: 810
    end_time: 991
- name: Cocoginol
  type: Suppository-type AsaCoco
  image: cocoginol.png
  price: 1000
  cm:
    id: w66x87VSQRc
    start_time: 615
    end_time: 764
- name: Extra Large Calorie Buner Type Kiryu 10L
  type: Calorie Burning Type AsaCoco
  image: kiryu_shiki_10l.png
  srp: 5000
  price: 1000
  cm:
    id: VcxeO4YfMXU
    start_time: 815
    end_time: 1034
- name: AsaCoco Spray
  type: Aerosol-type AsaCoco
  image: spray.png
  price: 893
  cm:
    id: ta6L-CarI3Q
    start_time: 934
    end_time: 1088
- name: Calorie Burner Type Kiryu
  type: Calorie Burning Type AsaCoco
  image: kiryu_shiki.png
  price: 1000
  cm:
    id: hq_WQmrZLKs
    start_time: 783
    end_time: 986
- name: Coco Furikake
  type: Furikake-type AsaCoco
  image: furikake.png
  price: 893
  cm:
    id: n2yIIhJl3mo
    start_time: 863
    end_time: 1068
- name: Shabuppy Turn
  type: Eating-type AsaCoco
  image: shabuppy_turn.png
  price: 500
  cm:
    id: n4-jb4qc_zA
    start_time: 803
    end_time: 910
