- name: AsaCoco Insurance
  type: Entry-type AsaCoco
  image: insurance.png
  price: 1000
  cm:
    id: OCGCgUmpd8k
    start_time: 957
    end_time: 1109
- name: AsaCoco Antenna
  type: Transmission-type AsaCoco
  image: antenna.jpeg
  srp: 2000
  price: 1000
  cm:
    id: RPEntBOmgi4
    start_time: 685
    end_time: 861
- name: AsaCoco Mist
  type: Air Filling Type AsaCoco
  image: mist.png
  price: 1000
  cm:
    id: kHsCSYBBSFc
    start_time: 810
    end_time: 991
- name: Cocoginol
  type: Suppository-type AsaCoco
  image: cocoginol.png
  price: 1000
  cm:
    id: w66x87VSQRc
    start_time: 615
    end_time: 764
- name: Extra Large Kiryu-shiki 10L
  type: Calorie Burner Type
  image: kiryu_shiki_10l.png
  srp: 5000
  price: 1000
  cm:
    id: VcxeO4YfMXU
    start_time: 815
    end_time: 1034
